version: '2.1'


services:
  db:
    image: postgres:9.5-alpine
    environment:
      POSTGRES_PASSWORD: app
      PGDATA : /var/lib/postgresql/data/pgdata
    volumes:
      - ./docker/files/pgdata:/var/lib/postgresql/data/pgdata
    ports:
      - "5448:5432"
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: ['python3', 'manage.py', 'runserver', '0.0.0.0:8000']
    hostname: presto-local.com
    volumes:
      - ./backend/src:/src:rw
    ports:
      - "8017:8000"
    depends_on:
      - db
    networks:
      default:
        aliases:
          - 'presto-local.com'
