MENU_ITEM_DISH_TYPE_SALAD = 'salad'
MENU_ITEM_DISH_TYPE_SOUP = 'soup'
MENU_ITEM_DISH_TYPE_SAUCE = 'sauce'
MENU_ITEM_DISH_TYPE_STEW = 'stew'
MENU_ITEM_DISH_TYPE_OTHER = 'other'

MENU_ITEM_DISH_TYPE_CHOICES = (
    (MENU_ITEM_DISH_TYPE_SALAD, 'Salad'),
    (MENU_ITEM_DISH_TYPE_SOUP, 'Soup'),
    (MENU_ITEM_DISH_TYPE_SAUCE, 'Sauce'),
    (MENU_ITEM_DISH_TYPE_STEW, 'Stew'),
    (MENU_ITEM_DISH_TYPE_OTHER, 'Other'),
)
